variable "identifier" {}
variable "subnet_ids" {}
variable "engine" {}
variable "engine_version" {}
variable "instance_class" {}
variable "storage_type" {}
variable "allocated_storage" {}
variable "vpc_security_group_ids" {}
variable "db_name" {}
variable "password" {}
variable "username" {}
